### ISSUE TITLE
add an option to view balances panel for address dashboard

### ISSUE THREAD

**Issue by banteg** [LlamaPay/interface#44]
### what i wish to see

this panel when i open a page for another wallet

<img width="729" alt="Screen Shot 2022-06-05 at 14 45 26" src="https://user-images.githubusercontent.com/4562643/172046842-6144af6a-3152-43c6-8ae6-77732dfb8fa9.png">

### how it can be done

there could be a request param that enables the panel, but without the "withdraw" and "top up" buttons if this is not the connected wallet: `https://llamapay.io/streams?chainId=1&address=ychad.eth&balances=true`

**Comment by 0xngmi** [comment]
Implemented
