### ISSUE TITLE
USDC Withdraw payload issue on Avalanche

### ISSUE THREAD

**Issue by snowsledge** [LlamaPay/interface#57]
Stream is set up for the streaming of USDC, but "Withdraw" txn payload is created for USDC.e, hence facing the error as shown below.

![image](https://user-images.githubusercontent.com/31395583/177078107-e96520d3-24a6-417d-8688-91c626cb26d9.png)

Error:
```
code: 3
data: "0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001473747265616d20646f65736e2774206578697374000000000000000000000000"
message: "execution reverted: stream doesn't exist"
```

**Comment by Nemusonaneko** [comment]
I was unable to replicate this issue. Is it still happening?

**Comment by Nemusonaneko** [comment]
> I've deleted my stream, withdrew, redeposit and started a new stream. Seems to fix the issue.

Got it. Let me know if there are any other issues or ways I could help. <3
